services:
  auth:
    build: ./auth
    ports:
      - "5002:5002"
    env_file:
      - ./auth/.env
    restart: unless-stopped

  inventory:
    build: ./inventory
    ports:
      - "4003:4003"
    env_file:
      - ./inventory/.env
    restart: unless-stopped

  sales:
    build: ./sales
    ports:
      - "4004:4004"
    env_file:
      - ./sales/.env
    environment:
      INVENTORY_SERVICE_URL: http://inventory:4003
    depends_on:
      - inventory
    restart: unless-stopped

  product1:
    build: ./product
    ports:
      - "4001:4001"
    env_file:
      - ./product/.env
    restart: unless-stopped

  product2:
    build: ./product
    ports:
      - "4006:4001"
    env_file:
      - ./product/.env
    restart: unless-stopped

  supplier:
    build: ./supplier
    ports:
      - "4002:4002"
    env_file:
      - ./supplier/.env
    restart: unless-stopped

  gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    env_file:
      - ./gateway/.env
    depends_on:
      - auth
      - inventory
      - sales
      - product1
      - product2
      - supplier
    restart: unless-stopped
